import dfa_class as dfac
#MERGED_B DFA 생성, STATE 3에서만 LIT_STRING으로
#3->Literal_String
alphabet_B={'"','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',' ','0','1','2','3','4','5','6','7','8','9'}
states_B={0,1,2,3}
tf_B=dict()

tf_B[(0,'"')]=1
tf_B[(1,'a')] =2
tf_B[(1,'b')] =2
tf_B[(1,'c')] =2
tf_B[(1,'d')] =2
tf_B[(1,'e')] =2
tf_B[(1,'f')] =2
tf_B[(1,'g')] =2
tf_B[(1,'h')] =2
tf_B[(1,'i')] =2
tf_B[(1,'j')] =2
tf_B[(1,'k')] =2
tf_B[(1,'l')] =2
tf_B[(1,'m')] =2
tf_B[(1,'n')] =2
tf_B[(1,'o')] =2
tf_B[(1,'p')] =2
tf_B[(1,'q')] =2
tf_B[(1,'r')] =2
tf_B[(1,'s')] =2
tf_B[(1,'t')] =2
tf_B[(1,'u')] =2
tf_B[(1,'v')] =2
tf_B[(1,'w')] =2
tf_B[(1,'x')] =2
tf_B[(1,'y')] =2
tf_B[(1,'z')] =2
tf_B[(1, 'A')] = 2
tf_B[(1, 'B')] = 2
tf_B[(1, 'C')] = 2
tf_B[(1, 'D')] = 2
tf_B[(1, 'E')] = 2
tf_B[(1, 'F')] = 2
tf_B[(1, 'G')] = 2
tf_B[(1, 'H')] = 2
tf_B[(1, 'I')] = 2
tf_B[(1, 'J')] = 2
tf_B[(1, 'K')] = 2
tf_B[(1, 'L')] = 2
tf_B[(1, 'M')] = 2
tf_B[(1, 'N')] = 2
tf_B[(1, 'O')] = 2
tf_B[(1, 'P')] = 2
tf_B[(1, 'Q')] = 2
tf_B[(1, 'R')] = 2
tf_B[(1, 'S')] = 2
tf_B[(1, 'T')] = 2
tf_B[(1, 'U')] = 2
tf_B[(1, 'V')] = 2
tf_B[(1, 'W')] = 2
tf_B[(1, 'X')] = 2
tf_B[(1, 'Y')] = 2
tf_B[(1, 'Z')] = 2
tf_B[(1, ' ')] = 2
tf_B[(1, '0')] = 2
tf_B[(1, '1')] = 2
tf_B[(1, '2')] = 2
tf_B[(1, '3')] = 2
tf_B[(1, '4')] = 2
tf_B[(1, '5')] = 2
tf_B[(1, '6')] = 2
tf_B[(1, '7')] = 2
tf_B[(1, '8')] = 2
tf_B[(1, '9')] = 2

tf_B[(2, 'a')] = 2
tf_B[(2, 'b')] = 2
tf_B[(2, 'c')] = 2
tf_B[(2, 'd')] = 2
tf_B[(2, 'e')] = 2
tf_B[(2, 'f')] = 2
tf_B[(2, 'g')] = 2
tf_B[(2, 'h')] = 2
tf_B[(2, 'i')] = 2
tf_B[(2, 'j')] = 2
tf_B[(2, 'k')] = 2
tf_B[(2, 'l')] = 2
tf_B[(2, 'm')] = 2
tf_B[(2, 'n')] = 2
tf_B[(2, 'o')] = 2
tf_B[(2, 'p')] = 2
tf_B[(2, 'q')] = 2
tf_B[(2, 'r')] = 2
tf_B[(2, 's')] = 2
tf_B[(2, 't')] = 2
tf_B[(2, 'u')] = 2
tf_B[(2, 'v')] = 2
tf_B[(2, 'w')] = 2
tf_B[(2, 'x')] = 2
tf_B[(2, 'y')] = 2
tf_B[(2, 'z')] = 2
tf_B[(2, 'A')] = 2
tf_B[(2, 'B')] = 2
tf_B[(2, 'C')] = 2
tf_B[(2, 'D')] = 2
tf_B[(2, 'E')] = 2
tf_B[(2, 'F')] = 2
tf_B[(2, 'G')] = 2
tf_B[(2, 'H')] = 2
tf_B[(2, 'I')] = 2
tf_B[(2, 'J')] = 2
tf_B[(2, 'K')] = 2
tf_B[(2, 'L')] = 2
tf_B[(2, 'M')] = 2
tf_B[(2, 'N')] = 2
tf_B[(2, 'O')] = 2
tf_B[(2, 'P')] = 2
tf_B[(2, 'Q')] = 2
tf_B[(2, 'R')] = 2
tf_B[(2, 'S')] = 2
tf_B[(2, 'T')] = 2
tf_B[(2, 'U')] = 2
tf_B[(2, 'V')] = 2
tf_B[(2, 'W')] = 2
tf_B[(2, 'X')] = 2
tf_B[(2, 'Y')] = 2
tf_B[(2, 'Z')] = 2
tf_B[(2, ' ')] = 2
tf_B[(2, '0')] = 2
tf_B[(2, '1')] = 2
tf_B[(2, '2')] = 2
tf_B[(2, '3')] = 2
tf_B[(2, '4')] = 2
tf_B[(2, '5')] = 2
tf_B[(2, '6')] = 2
tf_B[(2, '7')] = 2
tf_B[(2, '8')] = 2
tf_B[(2, '9')] = 2
tf_B[(2, '"')] = 3

start_state_B=0
accept_states_B={3}

Merged_B = dfac.DFA(states=states_B,alphabet=alphabet_B,transition_function=tf_B,start_state=start_state_B,accept_states=accept_states_B,state_number_to_state_contents={3:'Literal_String'})
#(눈)검정 완료